### ISSUE TITLE
Running shennina.py on Arch Linux

### ISSUE THREAD

**Issue by dale915** [mazen160/shennina#2]
Hello. 

I had some issues installing the default requirements so I used these : 

> pymetasploit3
> termcolor
> python-nmap
> requests
> flask
> tensorflow==2.8.0 (Instead of 2.7.3)
> tensorflow-estimator==2.7.0
> tensorflow-hub==0.12.0
> matplotlib==3.4.3
> pandas==1.1.5
> numpy==1.21.0 (Instead of 1.16.3)
> numpydoc==0.9.1

So the requirements installed well but when I run shennina.py I get these errors :  

> Traceback (most recent call last):
>   File "/home/arch1618033/HACKING_TOOLS/shennina/shennina.py", line 11, in <module>
>     import a3c_classes
>   File "/home/arch1618033/HACKING_TOOLS/shennina/classes/a3c_classes.py", line 4, in <module>
>     from tensorflow.python.keras import layers
>   File "/usr/lib/python3.10/site-packages/tensorflow/__init__.py", line 473, in <module>
>     keras._load()
>   File "/usr/lib/python3.10/site-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
>     module = importlib.import_module(self.__name__)
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/usr/lib/python3.10/site-packages/keras/__init__.py", line 25, in <module>
>     from keras import models
>   File "/usr/lib/python3.10/site-packages/keras/models.py", line 20, in <module>
>     from keras import metrics as metrics_module
>   File "/usr/lib/python3.10/site-packages/keras/metrics.py", line 24, in <module>
>     from keras import activations
>   File "/usr/lib/python3.10/site-packages/keras/activations.py", line 20, in <module>
>     from keras.layers import advanced_activations
>   File "/usr/lib/python3.10/site-packages/keras/layers/__init__.py", line 27, in <module>
>     from keras.engine.base_preprocessing_layer import PreprocessingLayer
>   File "/usr/lib/python3.10/site-packages/keras/engine/base_preprocessing_layer.py", line 19, in <module>
>     from keras.engine import data_adapter
>   File "/usr/lib/python3.10/site-packages/keras/engine/data_adapter.py", line 38, in <module>
>     import pandas as pd  # pylint: disable=g-import-not-at-top
>   File "/usr/lib/python3.10/site-packages/pandas/__init__.py", line 30, in <module>
>     from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
>   File "/usr/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
>     from pandas._libs.interval import Interval
>   File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
> ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

CAN ANYBODY HELP ME FIX THIS PLEASE ?

Some info about my system (Feel free to ask for more detail) : 

- Arch Linux
- Terminal Alacrity
- Python 3.10.8
- Pip 22.3.1

Thanks a lot :)

**Comment by davidne8645** [comment]
have you tried uninstalling numpy and reinstalling 
```
pip3 install --upgrade numpy
```
or
```
pip3 uninstall numpy
pip3 install numpy
```

**Comment by zAbuQasem** [comment]
Well you have 2 options in here:
1- Install python 3.9 then create a virtual environment and install the requirements in there.

2- Pull a python 3.9 docker image and install the tool in it

**Comment by dale915** [comment]
> have you tried uninstalling numpy and reinstalling
> 
> ```
> pip3 install --upgrade numpy
> ```
> 
> or
> 
> ```
> pip3 uninstall numpy
> pip3 install numpy
> ```

**pip3 install --upgrade numpy**  Worked for me. Thanks a lot.

**Comment by dale915** [comment]
> Well you have 2 options in here: 1- Install python 3.9 then create a virtual environment and install the requirements in there.
> 
> 2- Pull a python 3.9 docker image and install the tool in it

Will try it out and confirm but **pip3 install --upgrade numpy** worked for me

**Comment by hum4nG0D** [comment]
well I'm trying to install using python3.9 and virtual environment. But I'm still getting numpy building error.


Here is the output of `pip install -r requirement`:
```
Collecting pymetasploit3
  Using cached pymetasploit3-1.0.3-py2.py3-none-any.whl (33 kB)
Requirement already satisfied: termcolor in /home/user1/py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: python-nmap in /home/user1/py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (0.7.1)
Collecting requests
  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
Collecting flask
  Using cached Flask-2.2.2-py3-none-any.whl (101 kB)
Collecting tensorflow==2.7.3
  Using cached tensorflow-2.7.3-cp39-cp39-manylinux2010_x86_64.whl (495.6 MB)
Requirement already satisfied: tensorflow-estimator==2.7.0 in /home/user1/py3.9/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (2.7.0)
Collecting tensorflow-hub==0.12.0
  Using cached tensorflow_hub-0.12.0-py2.py3-none-any.whl (108 kB)
Collecting matplotlib==3.4.3
  Using cached matplotlib-3.4.3-cp39-cp39-manylinux1_x86_64.whl (10.3 MB)
Collecting pandas==1.1.5
  Using cached pandas-1.1.5-cp39-cp39-manylinux1_x86_64.whl (9.3 MB)
Collecting numpy==1.16.3
  Using cached numpy-1.16.3.zip (5.1 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpydoc==0.9.1
  Using cached numpydoc-0.9.1-py3-none-any.whl
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.21.0 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (0.29.0)
Collecting tensorboard~=2.6
  Using cached tensorboard-2.11.0-py3-none-any.whl (6.0 MB)
Collecting absl-py>=0.4.0
  Using cached absl_py-1.3.0-py3-none-any.whl (124 kB)
Requirement already satisfied: wrapt>=1.11.0 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (1.14.1)
Collecting google-pasta>=0.1.1
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Requirement already satisfied: wheel<1.0,>=0.32.0 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (0.37.1)
Collecting astunparse>=1.6.0
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Collecting opt-einsum>=2.3.2
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: libclang>=9.0.1 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (14.0.6)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (3.19.6)
Requirement already satisfied: typing-extensions>=3.6.6 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (4.4.0)
Requirement already satisfied: keras<2.8,>=2.7.0rc0 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (2.7.0)
Collecting h5py>=2.9.0
  Using cached h5py-3.7.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (4.5 MB)
Collecting keras-preprocessing>=1.1.1
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Requirement already satisfied: six>=1.12.0 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (1.16.0)
Collecting grpcio<2.0,>=1.24.3
  Using cached grpcio-1.51.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorflow==2.7.3->-r requirements.txt (line 6)) (2.0.7)
Collecting gast<0.5.0,>=0.2.1
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Requirement already satisfied: pillow>=6.2.0 in /home/user1/py3.9/lib/python3.9/site-packages (from matplotlib==3.4.3->-r requirements.txt (line 9)) (9.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /home/user1/py3.9/lib/python3.9/site-packages (from matplotlib==3.4.3->-r requirements.txt (line 9)) (2.8.2)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Requirement already satisfied: pyparsing>=2.2.1 in /home/user1/py3.9/lib/python3.9/site-packages (from matplotlib==3.4.3->-r requirements.txt (line 9)) (3.0.9)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Requirement already satisfied: pytz>=2017.2 in /home/user1/py3.9/lib/python3.9/site-packages (from pandas==1.1.5->-r requirements.txt (line 10)) (2022.7)
Collecting Jinja2>=2.3
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting sphinx>=1.6.5
  Using cached sphinx-6.0.0-py3-none-any.whl (3.0 MB)
Collecting retry
  Using cached retry-0.9.2-py2.py3-none-any.whl (8.0 kB)
Requirement already satisfied: msgpack in /home/user1/py3.9/lib/python3.9/site-packages (from pymetasploit3->-r requirements.txt (line 1)) (1.0.4)
Collecting charset-normalizer<3,>=2
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/user1/py3.9/lib/python3.9/site-packages (from requests->-r requirements.txt (line 4)) (1.26.13)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting itsdangerous>=2.0
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting importlib-metadata>=3.6.0
  Using cached importlib_metadata-5.2.0-py3-none-any.whl (21 kB)
Collecting click>=8.0
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting Werkzeug>=2.2.2
  Using cached Werkzeug-2.2.2-py3-none-any.whl (232 kB)
Requirement already satisfied: zipp>=0.5 in /home/user1/py3.9/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->flask->-r requirements.txt (line 5)) (3.11.0)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting imagesize>=1.3
  Using cached imagesize-1.4.1-py2.py3-none-any.whl (8.8 kB)
Collecting docutils<0.20,>=0.18
  Using cached docutils-0.19-py3-none-any.whl (570 kB)
Requirement already satisfied: sphinxcontrib-jsmath in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (1.0.1)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (1.1.5)
Requirement already satisfied: Pygments>=2.12 in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (2.13.0)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (2.0.0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (0.7.12)
Requirement already satisfied: packaging>=21.0 in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (22.0)
Requirement already satisfied: sphinxcontrib-devhelp in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (1.0.2)
Requirement already satisfied: sphinxcontrib-applehelp in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (1.0.2)
Collecting babel>=2.9
  Using cached Babel-2.11.0-py3-none-any.whl (9.5 MB)
Requirement already satisfied: snowballstemmer>=2.0 in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (2.2.0)
Requirement already satisfied: sphinxcontrib-qthelp in /home/user1/py3.9/lib/python3.9/site-packages (from sphinx>=1.6.5->numpydoc==0.9.1->-r requirements.txt (line 12)) (1.0.3)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorboard~=2.6->tensorflow==2.7.3->-r requirements.txt (line 6)) (0.6.1)
Collecting google-auth<3,>=1.6.3
  Using cached google_auth-2.15.0-py2.py3-none-any.whl (177 kB)
Requirement already satisfied: setuptools>=41.0.0 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorboard~=2.6->tensorflow==2.7.3->-r requirements.txt (line 6)) (65.3.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /home/user1/py3.9/lib/python3.9/site-packages (from tensorboard~=2.6->tensorflow==2.7.3->-r requirements.txt (line 6)) (1.8.1)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)
Collecting decorator>=3.4.2
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Requirement already satisfied: py<2.0.0,>=1.4.26 in /home/user1/py3.9/lib/python3.9/site-packages (from retry->pymetasploit3->-r requirements.txt (line 1)) (1.11.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/user1/py3.9/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow==2.7.3->-r requirements.txt (line 6)) (0.2.8)
Collecting cachetools<6.0,>=2.0.0
  Using cached cachetools-5.2.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/user1/py3.9/lib/python3.9/site-packages (from google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow==2.7.3->-r requirements.txt (line 6)) (4.9)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /home/user1/py3.9/lib/python3.9/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard~=2.6->tensorflow==2.7.3->-r requirements.txt (line 6)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /home/user1/py3.9/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow==2.7.3->-r requirements.txt (line 6)) (3.2.2)
Building wheels for collected packages: numpy
  Building wheel for numpy (setup.py): started
  Building wheel for numpy (setup.py): still running...
  Building wheel for numpy (setup.py): finished with status 'error'
  Running setup.py clean for numpy
Failed to build numpy
Installing collected packages: numpy, MarkupSafe, kiwisolver, itsdangerous, importlib-metadata, imagesize, idna, grpcio, google-pasta, gast, docutils, decorator, cycler, click, charset-normalizer, certifi, cachetools, babel, astunparse, absl-py, Werkzeug, tensorflow-hub, retry, requests, pandas, opt-einsum, matplotlib, markdown, keras-preprocessing, Jinja2, h5py, google-auth, sphinx, requests-oauthlib, pymetasploit3, flask, numpydoc, google-auth-oauthlib, tensorboard, tensorflow
  Attempting uninstall: numpy
    Found existing installation: numpy 1.24.1
    Uninstalling numpy-1.24.1:
      Successfully uninstalled numpy-1.24.1
  Running setup.py install for numpy: started
  Running setup.py install for numpy: finished with status 'error'
  Rolling back uninstall of numpy
  Moving to /home/user1/py3.9/bin/f2py
   from /tmp/pip-uninstall-b0d_wjsv/f2py
  Moving to /home/user1/py3.9/bin/f2py3
   from /tmp/pip-uninstall-b0d_wjsv/f2py3
  Moving to /home/user1/py3.9/bin/f2py3.9
   from /tmp/pip-uninstall-b0d_wjsv/f2py3.9
  Moving to /home/user1/py3.9/lib/python3.9/site-packages/numpy-1.24.1.dist-info/
   from /home/user1/py3.9/lib/python3.9/site-packages/~umpy-1.24.1.dist-info
  Moving to /home/user1/py3.9/lib/python3.9/site-packages/numpy.libs/
   from /home/user1/py3.9/lib/python3.9/site-packages/~umpy.libs
  Moving to /home/user1/py3.9/lib/python3.9/site-packages/numpy/
   from /home/user1/py3.9/lib/python3.9/site-packages/~umpy
```
